# Generated by Django 2.0.7 on 2018-07-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_problem_file_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='correct_cnt',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='try_cnt',
        ),
        migrations.AlterField(
            model_name='problem',
            name='correct_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='try_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
